### Dodaj nową książkę
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Wiedźmin",
  "author": { "id": 2 },
  "genre": "Fantasy",
  "isbn": "978-83-7460-123-4",
  "description": "Saga o Geralcie z Rivii.",
  "availableCopies": 5
}

### dodaj ksizkę
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Pan Tadeusz",
  "author": { "id": 3 },
  "genre": "Epopeja narodowa",
  "isbn": "978-83-12345-67-8",
  "description": "Klasyka literatury polskiej",
  "availableCopies": 7
}

### Dodaj nową książkę
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Lalka",
  "author": { "id": 4 },
  "genre": "Powieść",
  "isbn": "978-83-7654-321-0",
  "description": "Klasyka polskiej literatury realistycznej",
  "availableCopies": 3
}

### Aktualizuj książkę o ID 5
PUT http://localhost:8080/api/books/5
Content-Type: application/json

{
  "title": "Lalka (edycja poprawiona)",
  "author": { "id": 4 },
  "genre": "Powieść",
  "isbn": "978-83-7654-321-0",
  "description": "Edycja z poprawkami",
  "availableCopies": 4
}


### Pobierz wszystkie książki
GET http://localhost:8080/api/books
Accept: application/json


### Pobierz książkę po ID (np. 1)
GET http://localhost:8080/api/books/3
Accept: application/json

### Pobierz książkę po ID (np. 1)
GET http://localhost:8080/api/books/4
Accept: application/json




### Dodaj książkę
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "TestUsuwania",
  "author": { "id": 4 },
  "genre": "Test",
  "isbn": "978-83-12345-678-9",
  "description": "Test",
  "availableCopies": 7
}

### Usuń książkę o ID x TestUsuwanie
DELETE http://localhost:8080/api/books/6


