### Pobierz wszystkie wypożyczenia
GET http://localhost:8080/api/loans
Accept: application/json

### Wypożycz książkę (userId=1, bookId=1)
POST http://localhost:8080/api/loans/borrow?userId=1&bookId=1

### Zwrot książki (loanId=1)
POST http://localhost:8080/api/loans/return/1

### Wypożycz książkę (userId=2, bookId=3)
POST http://localhost:8080/api/loans/borrow?userId=1&bookId=1